include:
  - board: nice_nano@2.0.0
    shield: urchin_left
    snippet: zmk-ad-hoc-shield
    board-root: config
  - board: nice_nano@2.0.0
    shield: urchin_right
    snippet: zmk-ad-hoc-shield
    board-root: config
