name: Build Firmware

on: [push, pull_request, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Cache west modules
        uses: actions/cache@v4
        with:
          path: |
            modules
            zephyr
            bootloader
            zmk
          key: ${{ runner.os }}-build-v1-${{ hashFiles('**/west.yml', '**/build.yaml') }}

      - name: Install and Build
        uses: zmkfirmware/zmk-build-action@v3
        with:
          repository_path: zmk
          config_path: config
          install_modules: 'true'
          build_matrix_path: build.yaml
